services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:geekvape@db:5432/mydb

  db:
    image: postgres:15.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: geekvape
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
